version: '3'
services:
  central-user-database:
    image: danielmc02/central-user-database-server0:test2

  load-balancer:
    image: danielmc02/load-balancer-server0:test2
    ports:
      - "80:80"
      
  application-server:
    image: danielmc02/stateless-application-server0:test2
